# Generated by Django 3.0.8 on 2020-07-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200717_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='auctions.Listing')),
            ],
        ),
    ]
