# Generated by Django 3.1.1 on 2020-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_winner'),
        ('auctions', '0004_auto_20200714_1548'),
    ]

    operations = [
    ]
